module.exports = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#d5e3fd",
        "error-dim": "#4e0309",
        "on-secondary": "#f7f9ff",
        "on-error-container": "#752121",
        "surface-container-low": "#f0f4f7",
        background: "#f7f9fb",
        "tertiary-fixed": "#dcddfe",
        "on-primary": "#f6f7ff",
        "on-tertiary-fixed": "#393c55",
        tertiary: "#5a5d78",
        "on-secondary-container": "#435368",
        primary: "#515f74",
        "surface-container-high": "#e1e9ee",
        "on-tertiary-fixed-variant": "#555873",
        "on-primary-container": "#455367",
        "tertiary-fixed-dim": "#cdcfef",
        "secondary-dim": "#44546a",
        "on-tertiary": "#faf8ff",
        "primary-fixed-dim": "#c7d5ee",
        "inverse-surface": "#0b0f10",
        "on-error": "#fff7f6",
        "on-tertiary-container": "#4b4e69",
        "surface-container-highest": "#d9e4ea",
        "on-secondary-fixed": "#314055",
        "secondary-fixed": "#d3e4fe",
        "primary-dim": "#455368",
        "on-surface-variant": "#566166",
        "surface-bright": "#f7f9fb",
        "on-primary-fixed-variant": "#4e5c71",
        surface: "#f7f9fb",
        "secondary-fixed-dim": "#c5d6f0",
        outline: "#717c82",
        "on-primary-fixed": "#324054",
        error: "#9f403d",
        "surface-container-lowest": "#ffffff",
        secondary: "#506076",
        "surface-tint": "#515f74",
        "error-container": "#fe8983",
        "secondary-container": "#d3e4fe",
        "inverse-primary": "#d5e3fd",
        "outline-variant": "#a9b4b9",
        "on-secondary-fixed-variant": "#4d5d73",
        "inverse-on-surface": "#9a9d9f",
        "on-surface": "#2a3439",
        "surface-dim": "#cfdce3",
        "tertiary-container": "#dcddfe",
        "surface-container": "#e8eff3",
        "surface-variant": "#d9e4ea",
        "tertiary-dim": "#4e516c",
        "primary-container": "#d5e3fd",
        "on-background": "#2a3439",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["'Be Vietnam Pro'", "sans-serif"],
        headline: ["'Be Vietnam Pro'", "sans-serif"],
        body: ["'Be Vietnam Pro'", "sans-serif"],
        label: ["'Be Vietnam Pro'", "sans-serif"],
      },
    },
  },
};
