export const PATHS = {
  ONBOARDING: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  VERIFY_EMAIL: "/verify-email",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  RESET_PASSWORD_NEW: "/reset-password-new",
  LEARN_MORE: "/learn-more",
  TERMS: "/terms",
  PRIVACY: "/privacy",
  HOME: "/home",
  DISCOVERY: "/discovery",
  NOTIFICATIONS: "/notifications",
  BOOKMARKS: "/bookmarks",
  SETTINGS: "/settings",
  PROFILE: "/profile",
  USER_PROFILE: "/profile/:username",
  POST_DETAIL: "/posts/:postId",
  ADMIN_REPORTS: "/admin/reports",
  ADMIN_AI: "/admin/ai",
  ADMIN_RBAC: "/admin/rbac",
} as const;

export type AppPaths = (typeof PATHS)[keyof typeof PATHS];
